<?php
//MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW
//MWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMWMW
/**
 * @license
 * @copyright
 * @package {}
 * @version 1.0
 * @since Sep 10, 2010
 * @author text.phtml
 */
/*
 * Uncomment the return statement to disable this template */
// return false
/*
 *
 */
?>
<div class="bg2_middle">
    <div class="text">
	<?php echo $this->p('text') ?>
    </div>
</div>
<div class="bg2_bottom"></div>