<?php
/**
 * @license 
 * @copyright 
 * @package Cundd_Form_Standard
 * @version 1.0
 * @since Dec 1, 2009
 * @author daniel
 */
/* 
 * Uncomment the return statement to disable this template */
// return false
/*
 * 
 */
?>
<div class="clear"> </div><style>.clear{clear:both;float:none;}</style>
<div id="Cundd_Formular" class="CunddContent Cundd_Form_Standard_Submit">
<input type="submit" value="submit"/>
</div>